name: CI workflow

# Events
on: push

# List of jobs
jobs:
  test:
    # runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --force

      - name: Run the tests & code coverage
        run: npm test -- --coverage

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2
